### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by FabioZTessitore** [christian99salerno/Python#1]
devi fare il programma hello

**Comment by christian99salerno** [comment]
Ok

**Comment by christian99salerno** [comment]
Ma in che linguaggio perché in python l'ho già fatto

**Comment by FabioZTessitore** [comment]
hai fatto l'esempio, devi fare l'esercizio

2017-01-13 16:41 GMT+01:00 christian99salerno <notifications@github.com>:

**Comment by christian99salerno** [comment]
in che senso non comprendo mi perdoni può essere più chiaro

**Comment by FabioZTessitore** [comment]
Quello che hai fatto è lo stesso esempio che stava nei dialoghi

Alla fine del capitolo ci sono gli esercizi

Il 13 gen 2017 5:02 PM, "christian99salerno" <notifications@github.com> ha
scritto:

**Comment by christian99salerno** [comment]
ok adesso è chiaro

**Comment by FabioZTessitore** [comment]
metti il prompt dentro alla chiamata a raw_input()

**Comment by christian99salerno** [comment]
ok adesso lo metto
