### ISSUE TITLE
sfera

### ISSUE THREAD

**Issue by FabioZTessitore** [christian99salerno/Python#2]
la riga 3 è assolutamente inutile

**Comment by christian99salerno** [comment]
va bene la tolgo

**Comment by christian99salerno** [comment]
ho aggiustato e rimesso su github sia sfera che hello_name

**Comment by FabioZTessitore** [comment]
ok, ora prova a fare con la calcolatrice un calcolo del volume della sfera e vedi se il tuo programma da lo stesso risultato

**Comment by christian99salerno** [comment]
ok

**Comment by christian99salerno** [comment]
E' strano il volume mi esce 33,51ecc mentre il programma esce 25, ecc la superficie si trova invece

**Comment by christian99salerno** [comment]
questo se metto 2 come raggio

**Comment by FabioZTessitore** [comment]
non c'è niente di strano. C'è un problema nel tuo programma nel calcolo del volume

**Comment by christian99salerno** [comment]
Quale devo mettere per caso volume = (4/3) *  (math.pi) * (r*r *r)

**Comment by christian99salerno** [comment]
Cioè forse il problema sta nel cosa moltuplica prima o dopo

**Comment by FabioZTessitore** [comment]
No

Il 15 gen 2017 9:44 PM, "christian99salerno" <notifications@github.com> ha
scritto:

**Comment by christian99salerno** [comment]
E qual è il problema ? Non ci arrivo

**Comment by christian99salerno** [comment]
Forse salta una moltiplicazione come l'ho scritto e per questo esce un risultato diverso dalla calcolatrice e devo scriverlo in più passaggi
